{"time":"2025-04-17T21:04:39.393124921-04:00","level":"INFO","msg":"stream: starting","core version":"0.19.9","symlink path":"/scratch/network/pw5115/my_less_project/implicit-ins-improved/LESS/wandb/run-20250417_210439-e53aogg4/logs/debug-core.log"}
{"time":"2025-04-17T21:04:39.50129799-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:45197->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:04:41.551144478-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:55043->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:04:45.58633738-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39435->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:04:55.072088746-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:36306->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:05:14.529844706-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:35875->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:05:47.346064481-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:43521->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:06:47.347329242-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:45101->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:07:47.348472565-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:35034->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:08:47.349514407-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:33489->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:09:47.350304623-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:34336->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:10:47.35060217-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59154->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:11:47.350981709-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49838->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:12:47.351452346-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59566->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:13:47.35262735-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:58227->[::1]:53: read: connection refused"}
