{"time":"2025-04-17T21:26:15.052844783-04:00","level":"INFO","msg":"stream: starting","core version":"0.19.9","symlink path":"/scratch/network/pw5115/my_less_project/implicit-ins-improved/LESS/wandb/run-20250417_212615-lq43wpuy/logs/debug-core.log"}
{"time":"2025-04-17T21:26:15.15835273-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:33321->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:26:17.256762912-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:54899->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:26:21.839220396-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:33481->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:26:30.863367228-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59962->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:26:49.939825017-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:45909->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:27:27.971299159-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49657->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:28:27.972251858-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56009->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:29:27.972890972-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39817->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:30:27.973829026-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59674->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:31:27.974564776-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:33358->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:32:27.975277377-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52065->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:33:27.97605252-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:42512->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:34:27.976572295-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52269->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:35:27.977011826-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39460->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:36:27.977461433-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56674->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:37:27.978807856-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:55151->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:38:27.979141969-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:51826->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:39:27.980018039-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39653->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:40:27.981067215-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:53326->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:41:27.981512963-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:54443->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:27.982298083-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39250->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:27.982335637-04:00","level":"ERROR","msg":"Failed to load features, feature will default to disabled","error":"api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39250->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:27.983614576-04:00","level":"INFO","msg":"created new stream","id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.983628194-04:00","level":"INFO","msg":"stream: started","id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.983642025-04:00","level":"INFO","msg":"writer: Do: started","stream_id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.983657879-04:00","level":"INFO","msg":"handler: started","stream_id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.983646009-04:00","level":"INFO","msg":"sender: started","stream_id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.984751199-04:00","level":"INFO","msg":"stream: closing","id":"lq43wpuy"}
{"time":"2025-04-17T21:42:27.985640587-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:42430->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:30.172124279-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:35135->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:34.59929549-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49616->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:42:44.115749384-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:46979->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:43:01.531456371-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49920->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:43:40.35311507-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56613->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:44:40.354084808-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:53884->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:45:40.354486614-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:51619->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:46:40.355204881-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49137->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:47:40.355980143-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:42917->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:48:40.356301881-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59052->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:49:40.357610803-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:43052->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:50:40.35796437-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:37590->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:51:40.359094854-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:38134->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:52:27.985353288-04:00","level":"WARN","msg":"sender: taking a long time","seconds":600.000349756,"work":"WorkRecord(*service_go_proto.Record_Run); Control(mailbox_slot:\"plb9fl3x40tv\" always_send:true connection_id:\"127.0.0.1:53690\")"}
{"time":"2025-04-17T21:52:40.3594535-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52181->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:53:40.360650759-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:44684->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:54:40.361568886-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52148->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:55:40.362184811-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:55075->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:56:40.36276189-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52980->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:57:40.364068525-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:50825->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:40.365009162-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:41714->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:40.365044259-04:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:41714->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:40.365180407-04:00","level":"INFO","msg":"sender: succeeded after taking longer than expected","seconds":972.380196753,"work":"WorkRecord(*service_go_proto.Record_Run); Control(mailbox_slot:\"plb9fl3x40tv\" always_send:true connection_id:\"127.0.0.1:53690\")"}
{"time":"2025-04-17T21:58:40.365787189-04:00","level":"ERROR","msg":"sender: upsertConfig: RunRecord is nil"}
{"time":"2025-04-17T21:58:40.416726105-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:43128->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:42.756973317-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:37985->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:47.201621399-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49686->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:58:57.022278787-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:37135->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:59:15.257306248-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:34637->[::1]:53: read: connection refused"}
{"time":"2025-04-17T21:59:47.487389445-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:58118->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:00:47.488085249-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49404->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:01:47.489381765-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:55165->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:02:47.489778449-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:47109->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:03:47.490843073-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:46049->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:04:47.491162606-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:54673->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:05:47.492252734-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:36122->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:06:47.492920873-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:49841->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:07:47.493356566-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56220->[::1]:53: read: connection refused"}
{"time":"2025-04-17T22:08:47.494588664-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:36174->[::1]:53: read: connection refused"}
